### ISSUE TITLE
Throwing Errors.

### ISSUE THREAD

**Issue by williamhelme** [sebv/node-wd-sync#2]
Hi, 

I'm trying to emit an error to allow my tests to carry on without issuing an error log and canceling the current test but it's not working, could you help me out?

Here is the error log I'm getting if it's of any use:

Error: Error response status.
    at EventEmitter.webdriver._newError (/Users/Shared/git/node-webdriver-tests/node_modules/wd-sync/node_modules/wd/lib/webdriver.js:47:13)
    at IncomingMessage.webdriver._callbackWithDataBase (/Users/Shared/git/node-webdriver-tests/node_modules/wd-sync/node_modules/wd/lib/webdriver.js:162:25)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete as onMessageComplete (http.js:149:23)
    at Socket.socketOnData as ondata (http.js:1356:20)
    at TCP.onread (net.js:404:27)

Regards,
Will.

**Comment by sebv** [comment]
Sorry for the delay, summer slacking...

Cannot do too much without a Gist.

Sound like you should try to do that outside wd, I think some test framework let you do that.
