### ISSUE TITLE
Bug when I use phantomjs (ghostdriver) with node-wd-sync 1.2.4

### ISSUE THREAD

**Issue by kyo06** [sebv/node-wd-sync#23]
Dear Sir,

Sometimes the script throws an error when I use ghostdriver of phantomjs 
phantomjs.exe --webdriver=4444 &

C:\Users\user\workspace\node_modules\wd-sync\node_modules\fibers\futur
e.js:173
                                                throw(ex);
                                                      ^
Error: Error response status: 13.
    at Webdriver._newError (C:\Users\user\workspace\node_modules\wd-sy
nc\node_modules\wd\lib\webdriver.js:80:13)
    at C:\Users\user\workspace\node_modules\wd-sync\node_modules\wd\li
b\webdriver.js:119:29
    at C:\Users\user\workspace\node_modules\wd-sync\node_modules\wd\li
b\webdriver.js:391:5
    at Request._callback (C:\Users\user\workspace\node_modules\wd-sync
\node_modules\wd\lib\webdriver.js:281:7)
    at Request.self.callback (C:\Users\user\workspace\node_modules\wd-
sync\node_modules\wd\node_modules\request\index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\user\workspace\node_modules\wd-sy
nc\node_modules\wd\node_modules\request\index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\user\workspace\node_modul
es\wd-sync\node_modules\wd\node_modules\request\index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

Thank you for your attention

Best Regards

**Comment by sebv** [comment]
Cannot reproduce on Mac, Please provide code sample.
